### PR TITLE
Serve real images, not b64

### PR DESCRIPTION
**Pull request by samdroid-apps**
The samples viewer is now DOM based, so real images are easier to deal with than b64 images.

This means that we can reduce code complexity in the client!  End the race conditions and DOM thrashing!

We also get the images cached by the browser!!!  Zoom Zoom Zoom!

### CODE REVIEW

**Comment by samdroid-apps** [comment]
Requires https://github.com/walterbender/turtleblocksjs/pull/194

**Comment by samdroid-apps** [comment]
@walterbender, just pushed a fix for that :smile:

**Comment by tchx84** [comment]
@SAMdroid-apps did you test it?

**Comment by samdroid-apps** [comment]
I tested it on my computer.

Requires https://github.com/walterbender/turtleblocksjs/pull/194

**Comment by tchx84** [comment]
In general 3 things:
- please separate changes in different commits, as suggested in my comments.
- add a good rationale for what exactly are you trying to achieve, specially for these changes that store some kind of metadata in the FS.
- send a clean new PR.

**Comment by samdroid-apps** [comment]
> - add a good rationale for what exactly are you trying to achieve, specially for these changes that store some kind of metadata in the FS.

Hum, I'm not sure what changes store metadata in the FS.

**Comment by samdroid-apps** [comment]
Replaced by #4

**Pull request closed without merging**
